AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'sorbet/**/*'
    - 'tmp/**/*'
    - 'bin/tapioca'

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 40
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 220
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 17

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'test/**/*'

Metrics/ModuleLength:
  Max: 150
  Exclude:
    - 'test/**/*'

Metrics/ParameterLists:
  Max: 7

Metrics/PerceivedComplexity:
  Max: 17

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false
