keys:
  deploy_pipeline:
    description: "Staging Deployment Workflow"
    transforms:
      response:
        mask_values:
          whitelist: []
    allowed:
      - method: POST
        path: "/v2/apps/:app_id/deployments"
        resource_ids: ["abc-123-staging-id"]
      - method: GET
        path: "/v2/apps/:app_id/envs"
        resource_ids: ["abc-123-staging-id"]
        transforms:
          response:
            mask_values:
              whitelist: [todo]
